function export_cpp_fixture(outFile)
%EXPORT_CPP_FIXTURE  Write the run_demo scenario and MATLAB's results for the C++ tests.
%   Same TLE, station and settings as scripts/run_demo.m. The C++ tests
%   (cpp/tests/test_windows.cpp) must reproduce these numbers.
%   Run after changing anything listed in codegen/cpp_inputs.txt; the output file
%   is committed and stamped with inputsHash(), which scripts/check_cpp_fixture.py,
%   the pre-commit hook and CI compare against the current sources.
%   The scenario is fixed here on purpose (not loadConfig), so a local .env
%   cannot change the committed numbers.
setup();
if nargin < 1
    outFile = fullfile(fileparts(fileparts(mfilename('fullpath'))), '..', 'cpp', 'tests', 'data', 'demo_reference.txt');
end
gs  = [45.45810, -73.64031, 50];      % Loyola; altitude is a placeholder
minElev = 10;  horizonH = 24;  stepSec = 30;  refineSec = 1;

l1 = TLEData.withChecksum("1 25544U 98067A   24001.50000000  .00016717  00000-0  10270-3 0  9999");
l2 = TLEData.withChecksum("2 25544  51.6416 247.4627 0006703 130.5360 325.0288 15.50377579 26629");
tle = TLEData.parse(l1 + newline + l2, "fixture");

tleFile = tempname + ".tle";  writelines(["ISS"; l1; l2], tleFile);
src  = FileTLESource(tleFile);
prop = SGP4Propagator();
svc  = PropagationService(src, prop, NowFcn=@() tle.epoch);
calc = CommunicationWindowCalculator(svc, gs(1), gs(2), gs(3), MinElevationDeg=minElev, ...
            HorizonHours=horizonH, StepSec=stepSec, PeakRefineStepSec=refineSec);
svc.checkTLE();
T = calc.windowTable();
delete(tleFile);

if ~isfolder(fileparts(outFile)), mkdir(fileparts(outFile)); end
fid = fopen(outFile, 'w');
c = onCleanup(@() fclose(fid));
fprintf(fid, '# Generated by matlab/tests/export_cpp_fixture.m - do not edit.\n');
fprintf(fid, 'inputs_sha256 %s\n', inputsHash());
fprintf(fid, 'tle1 %s\ntle2 %s\n', l1, l2);
fprintf(fid, 'epoch_posix %.6f\n', posixtime(tle.epoch));
fprintf(fid, 'gs %.9f %.9f %.3f\n', gs);
fprintf(fid, 'params %.6f %.6f %.6f %.6f\n', minElev, horizonH, stepSec, refineSec);
for k = 1:height(T)     % startPosix endPosix maxElevDeg
    fprintf(fid, 'window %.6f %.6f %.6f\n', posixtime(T.Start(k)), posixtime(T.End(k)), T.MaxElevationDeg(k));
end
tt = tle.epoch + minutes([0 17 95 600 1234]');    % ECEF samples: t, x y z [m]
pos = prop.propagate(tt);
for k = 1:numel(tt)
    fprintf(fid, 'ecef %.6f %.6f %.6f %.6f\n', posixtime(tt(k)), pos.position(k, :));
end
fprintf('Wrote %d windows and %d ECEF samples to %s\n', height(T), numel(tt), outFile);
end
